# Translation interface
#######################

liip_translation_interface:
    path:     /list
    defaults: { _controller: LiipTranslationBundle:Translation:index }

liip_translation_filter:
    path:     /filter
    defaults: { _controller: LiipTranslationBundle:Translation:filter }
    methods:  [POST]

liip_translation_resetfilter:
    path:     /filter-reset
    defaults: { _controller: LiipTranslationBundle:Translation:clearFilter }

liip_translation_edit:
    path:     /edit/{locale}/{domain}/{key}
    defaults: { _controller: LiipTranslationBundle:Translation:edit }

liip_translation_inline_edit:
    path:     /inline-edit/
    defaults: { _controller: LiipTranslationBundle:Translation:inlineEdit }

liip_translation_remove:
    path:     /remove/{locale}/{domain}/{key}
    defaults: { _controller: LiipTranslationBundle:Translation:remove }

liip_translation_cache_clear:
    path:     /cache-clear
    defaults: { _controller: LiipTranslationBundle:Translation:cacheClear }

liip_translation_export:
    path:     /export
    defaults: { _controller: LiipTranslationBundle:Translation:export }