security:
  role_hierarchy:
    ROLE_TRANSLATION_ADMIN: [ROLE_TRANSLATION_ALL_DOMAINS, ROLE_TRANSLATION_ALL_LOCALES]
    ROLE_TRANSLATION_ALL_DOMAINS: [] # Specific domains such as ROLE_TRANSLATION_DOMAIN_MESSAGES are created dynamically and cannot be listed here
    ROLE_TRANSLATION_ALL_LOCALES: [] # Specific locales such as ROLE_TRANSLATION_LOCALE_FR_CH are created dynamically and cannot be listed here