parameters:
    translator.class: Liip\TranslationBundle\Translation\Translator

services:
    liip.translation.repository:
        class: Liip\TranslationBundle\Repository\UnitRepository
        arguments: ["%liip_translation_config%", "@translator", "@liip.translation.persistence"]

    liip.translation.security:
        class: Liip\TranslationBundle\Security\Security
        arguments: ["%liip_translation_config%"]

    liip.translation.persistence:
        class: %liip.translation.persistence.class%
        arguments: ["%liip.translation.persistence.options%"]

    liip.translation.loader:
        class: Liip\TranslationBundle\Translation\Loader
        arguments: ["@liip.translation.repository"]

    liip.translation.importer:
        class: Liip\TranslationBundle\Import\FileImporter
        arguments: ["@liip.translation.repository", "@session", "@translator"]

    liip.xliff.loader:
        class: Liip\TranslationBundle\Translation\Loader\XliffFileLoader