parameters:
    translator.class: Liip\TranslationBundle\Translation\Translator

services:

    liip.translation.manager:
        class: Liip\TranslationBundle\Model\Manager
        arguments: ["%liip_translation_config%", "@translator", "@liip.translation.storage"]

    liip.translation.storage:
        class: Liip\TranslationBundle\Model\Storage\Storage
        arguments: ["@liip.translation.persistance"]

    liip.translation.persistance:
        class: Liip\TranslationBundle\Model\Storage\Persistence\YamlFilePersistence
        arguments: [folder: "%kernel.root_dir%/data/translations"]

    liip.translation.storage.loader:
        class: Liip\TranslationBundle\Model\Storage\Loader
        arguments: ["@liip.translation.storage"]

    liip.xliff.loader:
        class: Liip\TranslationBundle\Translation\Loader\XliffFileLoader