parameters:
    translator.class: Liip\TranslationBundle\Translation\DualModeTranslator

services:
    liip.translation.manager:
        class: Liip\TranslationBundle\Manager\Manager
        arguments: ["%liip_translation_config%", "@translator"]