parameters:
    translator.class: Liip\TranslationBundle\Translation\Translator

services:
    liip.translation.manager:
        class: Liip\TranslationBundle\Model\Manager
        arguments: ["%liip_translation_config%", "@translator", "@liip.translation.storage"]

    liip.translation.storage:
        class: Liip\TranslationBundle\Storage\Storage
        arguments: ["@liip.translation.persistance"]

    liip.translation.persistance:
        class: %liip.translation.persistance.class%
        arguments: ["%liip.translation.persistance.options%"]

    liip.translation.loader:
        class: Liip\TranslationBundle\Translation\Loader
        arguments: ["@liip.translation.storage"]

    liip.translation.importer:
        class: Liip\TranslationBundle\Model\Importer\Importer
        arguments: ["@session", "@liip.translation.storage", "@translator"]

    liip.xliff.loader:
        class: Liip\TranslationBundle\Translation\Loader\XliffFileLoader