services:
    liip.translation.translator:
        parent: translator.default
        class: Liip\TranslationBundle\Translation\Translator

    liip.translation.repository:
        class: Liip\TranslationBundle\Repository\UnitRepository
        arguments: ["%liip_translation_config%", "@liip.translation.translator", "@liip.translation.persistence", "@liip.translation.security"]

    liip.translation.security:
        class: Liip\TranslationBundle\Security\Security
        arguments: ["%liip_translation_config%", @?security.context]

    liip.translation.persistence:
        class: %liip.translation.persistence.class%
        arguments: ["%liip.translation.persistence.options%"]

    liip.translation.loader:
        class: Liip\TranslationBundle\Translation\Loader
        arguments: ["@liip.translation.repository"]
        tags:
            - { name: "translation.loader", alias: "liip" }

    liip.translation.session_importer:
        class: Liip\TranslationBundle\Import\SessionImporter
        arguments: ["@liip.translation.repository", "@session", "@liip.translation.translator"]

    liip.translation.symfony_importer:
        class: Liip\TranslationBundle\Import\SymfonyImporter
        arguments: ["%liip_translation_config%", "@liip.translation.translator", "@liip.translation.repository"]

    liip.translation.exporter:
        class: Liip\TranslationBundle\Export\ZipExporter

    liip.translation.xliff.loader:
        class: Liip\TranslationBundle\Translation\Loader\XliffFileLoader

    liip.translation.filter:
        class: Liip\TranslationBundle\Filter\FilterManager
        arguments: ["%liip_translation_config%", "@session", "@liip.translation.repository"]
