parameters:
    translator.class: Liip\TranslationBundle\Translation\Translator

services:

    liip.translation.manager:
        class: Liip\TranslationBundle\Model\Manager
        arguments: ["%liip_translation_config%", "@translator", "@liip.translation.storage"]

    liip.translation.storage:
        class: Liip\TranslationBundle\Model\Storage\Storage

    liip.translation.storage.loader:
        class: Liip\TranslationBundle\Model\Storage\Loader
        arguments: ["@liip.translation.storage"]

    liip.xliff.loader:
        class: Liip\TranslationBundle\Translation\Loader\XliffFileLoader